### ISSUE TITLE
Start Phase 2

### ISSUE THREAD

**Issue by aung-zan** [aung-zan/Hospital-Appointment#7]
### Description
Start the tasks of phase 2.

### Tasks
- [ ] Send mail to check the schedule.
- [ ] Excel upload/download functions for the doctor.
- [ ] Excel download functions for the schedule.
